[package]
name = "accounts"
version = "0.1.0"
authors = ["Takumi Karibe <takumi.k.5610@gmail.com>"]
edition = "2018"

[dependencies]
rand = ""
core = { package = "core", path = "../core/" }
utils = { package = "utils", path = "../utils/" }
