[package]
name = "nodes"
version = "0.1.0"
authors = ["Takumi Karibe <takumi.k.5610@gmail.com>"]
edition = "2018"

[dependencies]
chrono = ""

core = { package = "core", path = "../core/" }
accounts = { package = "accounts", path = "../accounts/" }
utils = { package = "utils", path = "../utils/" }
